import AppKit
import UniformTypeIdentifiers

/// Единственное место, где читается NSPasteboard.
///
/// Отдельный тип, потому что здесь сосредоточена вся политика приватности
/// и вся возня с приоритетом типов данных. Читатель ничего не пишет и не хранит.
struct PasteboardReader {
    /// Маркер собственных записей: даже если changeCount проскочит,
    /// свой же элемент повторно в историю не попадёт.
    static let ownershipType = NSPasteboard.PasteboardType("app.clipflow.internal")

    /// De-facto стандарт (nspasteboard.org), которому следуют менеджеры паролей
    /// и утилиты, не желающие попадать в историю буфера.
    private static let opaqueTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
    ]

    private static let imageTypeCandidates: [(NSPasteboard.PasteboardType, ImageFormat)] = [
        (.png, .png),
        (NSPasteboard.PasteboardType(UTType.jpeg.identifier), .jpeg),
        (NSPasteboard.PasteboardType(UTType.gif.identifier), .gif),
        (NSPasteboard.PasteboardType("public.heic"), .heic),
        (.tiff, .tiff),
    ]

    var capturesImages: Bool
    var excludedBundleIDs: Set<String>

    /// Возвращает nil, если читать нечего или читать нельзя.
    /// Никогда не бросает: одно битое значение в буфере не должно ронять цикл мониторинга.
    func read(from pasteboard: NSPasteboard) -> ClipboardCapture? {
        let rawTypes = Set((pasteboard.types ?? []).map(\.rawValue))
        guard rawTypes.isDisjoint(with: Self.opaqueTypes) else {
            Log.monitor.debug("Skipping pasteboard: marked as concealed or transient")
            return nil
        }
        guard !rawTypes.contains(Self.ownershipType.rawValue) else { return nil }

        let source = currentSourceApp()
        if let bundleID = source?.bundleID, excludedBundleIDs.contains(bundleID) {
            Log.monitor.debug("Skipping pasteboard from excluded app \(bundleID, privacy: .public)")
            return nil
        }

        // Текст приоритетнее изображения: приложения вроде Keynote кладут
        // и то и другое, а пользователь почти всегда копировал текст.
        if let text = readText(from: pasteboard) {
            return ClipboardCapture(payload: .text(text), source: source, capturedAt: .now)
        }
        if capturesImages, let image = readImage(from: pasteboard) {
            return ClipboardCapture(payload: image, source: source, capturedAt: .now)
        }
        return nil
    }

    private func readText(from pasteboard: NSPasteboard) -> String? {
        guard let text = pasteboard.string(forType: .string) else { return nil }
        // Пустое/пробельное содержимое не имеет смысла в истории,
        // но сам текст сохраняем без изменений — trim только для проверки.
        guard !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return nil }
        return text
    }

    private func readImage(from pasteboard: NSPasteboard) -> ClipboardCapture.Payload? {
        // Ищем компактный формат раньше TIFF: скриншот в TIFF занимает
        // десятки мегабайт, тот же кадр в PNG — единицы.
        for (type, format) in Self.imageTypeCandidates {
            if let data = pasteboard.data(forType: type), !data.isEmpty {
                return .image(data: data, format: format)
            }
        }

        // Скопированный в Finder файл изображения.
        if let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [
            .urlReadingFileURLsOnly: true
        ]) as? [URL] {
            for url in urls {
                guard let type = UTType(filenameExtension: url.pathExtension),
                      type.conforms(to: .image),
                      let data = try? Data(contentsOf: url, options: .mappedIfSafe),
                      !data.isEmpty
                else { continue }
                return .image(data: data, format: .from(utType: type))
            }
        }
        return nil
    }

    private func currentSourceApp() -> SourceApp? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        return SourceApp(bundleID: app.bundleIdentifier, name: app.localizedName)
    }
}
